"""empty message

Revision ID: 5a585ebc4d15
Revises: dfdb5691d5b5
Create Date: 2024-09-12 19:25:27.889468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a585ebc4d15'
down_revision: Union[str, None] = 'dfdb5691d5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_priority', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_priority', 'tasks', ['priority'])
    # ### end Alembic commands ###
